name: tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - run: python -m pip install .
      shell: bash
    - run: check-yamlschema -v tests/test.yaml .pre-commit-config.yaml .pre-commit-hooks.yaml .github/workflows/pre-commit.yml
      shell: bash
